parameters:
  env: ''
  azuresubscription: ''
  webappname: ''
  webapiname: ''

jobs:
  - deployment: deployNetCoreToLinux
    displayName: Deploy Web Api
    environment: ${{ parameters.env }}
    pool:
      vmImage: 'ubuntu-18.04'
    container:
        image: mcr.microsoft.com/azure-powershell:latest
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureRmWebAppDeployment@4
              displayName: "Deploy API"
              inputs:
                azureSubscription: ${{ parameters.azuresubscription }}
                appType: webAppLinux
                WebAppName: ${{ parameters.webapiname }}
                packageForLinux: "$(Pipeline.Workspace)/**/FastCarzWebApi.zip"
                RemoveAdditionalFilesFlag: true
                ExcludeFilesFromAppDataFlag: true
                TakeAppOfflineFlag: true
            - task: AzureRmWebAppDeployment@4
              displayName: "Deploy Web App"
              inputs:
                azureSubscription: ${{ parameters.azuresubscription }}
                appType: webAppLinux
                WebAppName: ${{ parameters.webappname }}
                packageForLinux: "$(Pipeline.Workspace)/**/FastCarzWebApp.zip"
                RemoveAdditionalFilesFlag: true
                ExcludeFilesFromAppDataFlag: true
                TakeAppOfflineFlag: true
