jobs:
  - job: AspNetCore
    pool:
      vmImage: 'ubuntu-20.04'
    container:
        image: mcr.microsoft.com/dotnet/sdk:3.1
    steps:
      - task: DotNetCoreCLI@2
        displayName: build
        inputs:
          command: 'build'
          arguments: '-c $(buildConfiguration)'
          projects: "**/*.sln"
          zipAfterPublish: True

      - task: DotNetCoreCLI@2
        displayName: test
        inputs:
          command: test
          projects: '**/*Tests/*.csproj'
          arguments: '-c $(buildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: 'archive'
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: |
            **/*.csproj
            !**/*.Tests.csproj
          arguments: '-o $(Build.ArtifactStagingDirectory)/'
          zipAfterPublish: true
          modifyOutputPath: true

      - task: PublishBuildArtifa  cts@1
        displayName: "Publish"
        inputs:
          PathtoPublish: "$(build.artifactstagingdirectory)"
          ArtifactName: "$(ArtifactName)"
          FileCopyOptions: "/XF *Test* "
        condition: succeededOrFailed()
