jobs:
  - job: AspNetCore
    pool:
      vmImage: 'ubuntu-20.04'
    container:
        image: mcr.microsoft.com/dotnet/sdk:3.1
    steps:
      - task: NuGetToolInstaller@0
        displayName: "Use NuGet"
        inputs:
          versionSpec: 4.4.1

      # Replaces NuGet restore
      - task: DotNetCoreCLI@2
        displayName: dotnet restore
        inputs:
          command: restore
          projects: "**/*.sln"
          feedsToUse: 'select'
          includeNuGetOrg: true

      # - task: NuGetCommand@2
      #   displayName: "NuGet restore"
      #   inputs:
      #     restoreSolution: "$(Parameters.solution)"
      
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '--configuration $(buildConfiguration) --platform $(BuildPlatform) --arch x64'
          projects: |
            "**/*.sln"
            
      # - task: MSBuild@1
      #   inputs:
      #     solution: '**/*.sln'
      #     msbuildArchitecture: 'x64'
      #     platform: "$(BuildPlatform)"
      #     configuration: "$(BuildConfiguration)"

      - task: VSTest@2
        displayName: "Test"
        inputs:
          testAssemblyVer2: |
            **\*test*.dll
            !**\obj\**
            platform: '$(BuildPlatform)'
            configuration: '$(BuildConfiguration)'

      - task: whitesource.whiteSource-bolt-v2.bolt.wss.WhiteSource@21
        displayName: WhiteSource
        inputs:
          projectName: "$(SourceBranchName)"

      - task: ArchiveFiles@2
        displayName: 'Archive FastCarzWebApp'
        inputs:
          rootFolderOrFile: $(System.DefaultWorkingDirectory)\app\DevOpsTest\FastCarzWebApp\bin\$(BuildConfiguration)\netcoreapp3.1
          includeRootFolder: false
          archiveFile: '$(Build.ArtifactStagingDirectory)/FastCarzWebApp.zip'

      - task: ArchiveFiles@2
        displayName: 'Archive FastCarzWebApi'
        inputs:
          rootFolderOrFile: $(System.DefaultWorkingDirectory)\app\DevOpsTest\FastCarzWebApi\bin\$(BuildConfiguration)\netcoreapp3.1
          includeRootFolder: false
          archiveFile: '$(Build.ArtifactStagingDirectory)/FastCarzWebApi.zip'

      - task: PublishBuildArtifacts@1
        displayName: "Publish"
        inputs:
          PathtoPublish: "$(build.artifactstagingdirectory)"
          ArtifactName: "$(Parameters.ArtifactName)"
        condition: succeededOrFailed()
