# Yaml pipeline demonstrating the use of containers as azdo agents
# Always a good idea to use the pipeline lineage in the runtime name
name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - master
    - main

variables:
  BuildConfiguration: Release
  ArtifactName: drop

stages:
  - stage: build
    jobs:
      - template: templates\job-build.yml

  - stage: dev
    dependsOn: build
    jobs:
      - template: templates\job-deploy.yml
        parameters:
          env: dev
          azuresubscription: dev-sub-01
          webappname: webapp-pi-dev
          webapiname: webapi-pi-dev